# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d97235e6f2cc6e1a66a65a36c9fef04387a3c65ad95e8e463c4744e6674c60d31591537f743b8dbb1c45d391659688349adefdb9a682151b531a19565980d6d

test:
  secret_key_base: 430fc41245003a370b7b81bf31c2836aca4ac7e3c27d7e55fdddc2c1dd5557e6228db1a3f08d0aa968c6aa254b4aa33bac072eb5aa29ec4466c2f61b6d3ae8b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
